[package]
name = "modus_ponens"
version = "0.11.0"
authors = ["Enrique PÃ©rez Arnaud <enrique@cazalla.net>"]
edition = "2018"

[dependencies]
log = "0.4"
env_logger = "0.7.1"
pest = "2.1.2"
pest_derive = "2.1.0"
bumpalo = "3.2.1"
proc-macro2 = "1.0"
quote = "1.0"
syn = "1.0"